import { readFile, writeFile } from 'node:fs/promises';
import { origin, repository, pages } from './site.mjs';

const root = new URL('../../', import.meta.url);
const { version } = JSON.parse(await readFile(new URL('package.json', root), 'utf8'));
const escape = value => value.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;');
const check = process.argv.includes('--check');
async function output(path, content) {
  const url = new URL(path, root);
  if (check) {
    if (await readFile(url, 'utf8') !== content) throw new Error(`${path} is stale. Run node scripts/landing/metadata.mjs`);
  } else await writeFile(url, content);
}
for (const page of pages) {
  const url = origin + page.path;
  const image = `${origin}/assets/share/${page.image}`;
  const schema = {
    '@context': 'https://schema.org',
    '@graph': [
      { '@type': 'WebSite', '@id': `${origin}/#website`, url: `${origin}/`, name: 'Warden', inLanguage: 'en' },
      { '@type': 'WebPage', '@id': `${url}#page`, url, name: page.title, description: page.description,
        inLanguage: 'en', isPartOf: { '@id': `${origin}/#website` }, about: { '@id': `${origin}/#software` } },
      { '@type': 'SoftwareApplication', '@id': `${origin}/#software`, name: 'Warden',
        url: `${origin}/`, applicationCategory: 'SecurityApplication', operatingSystem: 'macOS, Windows, Linux',
        softwareVersion: version, releaseNotes: `${repository}/releases/tag/v${version}`, downloadUrl: `${repository}/releases/latest`,
        license: `${repository}/blob/main/LICENSE`, isAccessibleForFree: true,
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
        description: 'Control what connected AI tools can share with rules you write.',
        sameAs: [repository] },
    ],
  };
  const meta = (key, value, property = false) => `<meta ${property ? 'property' : 'name'}="${key}" content="${escape(value)}">`;
  const block = [
    '<!-- site-metadata:start (generated by scripts/landing/metadata.mjs) -->',
    `<title>${escape(page.title)}</title>`, meta('description', page.description),
    `<link rel="canonical" href="${url}">`,
    meta('robots', 'index, follow, max-image-preview:large'), meta('theme-color', '#080808'),
    ...Object.entries({ 'og:title': page.socialTitle, 'og:description': page.description,
      'og:type': 'website', 'og:url': url, 'og:site_name': 'Warden', 'og:locale': 'en_US',
      'og:image': image, 'og:image:type': 'image/png', 'og:image:width': '1200',
      'og:image:height': '630', 'og:image:alt': page.imageAlt }).map(([key, value]) => meta(key, value, true)),
    ...Object.entries({ 'twitter:card': 'summary_large_image', 'twitter:title': page.socialTitle,
      'twitter:description': page.description, 'twitter:image': image, 'twitter:image:alt': page.imageAlt }).map(([key, value]) => meta(key, value)),
    `<script type="application/ld+json">\n${JSON.stringify(schema, null, 2).replaceAll('<', '\\u003c')}\n</script>`,
    '<!-- site-metadata:end -->',
  ].join('\n');
  const path = `landing/${page.file}`;
  const html = await readFile(new URL(path, root), 'utf8');
  if (!html.includes('<!-- site-metadata:start')) throw new Error(`Missing metadata slot in ${path}`);
  await output(path, html.replace(/<!-- site-metadata:start[\s\S]*?<!-- site-metadata:end -->/, block));
}
await output('landing/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${pages.map(p => `  <url><loc>${origin}${p.path}</loc></url>`).join('\n')}\n</urlset>\n`);
await output('landing/robots.txt', `User-agent: *\nAllow: /\n\nSitemap: ${origin}/sitemap.xml\n`);
console.log(check ? 'Site metadata is current.' : 'Updated page metadata, sitemap and robots.txt.');
